export const RECEIVE_USER_TV_SHOWS = 'RECEIVE_USER_TV_SHOWS'
export const REQUEST_USER_TV_SHOWS = 'REQUEST_USER_TV_SHOWS'

export const REQUEST_TV_SHOW = 'REQUEST_TV_SHOW'
export const RECEIVE_TV_SHOW = 'RECEIVE_TV_SHOW'

export const REQUEST_LAST_EPISODE_NOT_SEEN = 'REQUEST_LAST_EPISODE_NOT_SEEN'

export const REQUEST_REMOVE_TV_SHOW_FROM_ARCHIVE = 'REQUEST_REMOVE_TV_SHOW_FROM_ARCHIVE'
export const RECEIVE_REMOVE_TV_SHOW_FROM_ARCHIVE = 'RECEIVE_REMOVE_TV_SHOW_FROM_ARCHIVE'